# Form implementation generated from reading ui file 'Auto.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Autor_MainWindow(object):
    def setupUi(self, Autor_MainWindow):
        Autor_MainWindow.setObjectName("Autor_MainWindow")
        Autor_MainWindow.resize(400, 600)
        Autor_MainWindow.setMinimumSize(QtCore.QSize(400, 600))
        Autor_MainWindow.setMaximumSize(QtCore.QSize(400, 600))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../Logo.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        Autor_MainWindow.setWindowIcon(icon)
        Autor_MainWindow.setStyleSheet("background-color: #001524;")
        Autor_MainWindow.setIconSize(QtCore.QSize(22, 24))
        self.centralwidget = QtWidgets.QWidget(Autor_MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Image = QtWidgets.QLabel(self.centralwidget)
        self.Image.setGeometry(QtCore.QRect(130, -30, 131, 171))
        self.Image.setAccessibleDescription("")
        self.Image.setText("")
        self.Image.setPixmap(QtGui.QPixmap("../../../Logo.png"))
        self.Image.setObjectName("Image")
        self.btn_phone = QtWidgets.QLineEdit(self.centralwidget)
        self.btn_phone.setGeometry(QtCore.QRect(50, 250, 300, 60))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_phone.setFont(font)
        self.btn_phone.setStyleSheet("border: 2px solid #ffff00;\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 30px\n"
"")
        self.btn_phone.setText("")
        self.btn_phone.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.btn_phone.setObjectName("btn_phone")
        self.btn_password = QtWidgets.QLineEdit(self.centralwidget)
        self.btn_password.setGeometry(QtCore.QRect(50, 360, 300, 60))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_password.setFont(font)
        self.btn_password.setStyleSheet("border: 2px solid #ffff00;\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 30px\n"
"")
        self.btn_password.setText("")
        self.btn_password.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.btn_password.setObjectName("btn_password")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(50, 480, 300, 60))
        font = QtGui.QFont()
        font.setFamily("Gill Sans Ultra Bold")
        font.setPointSize(18)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("color: rgb(170, 85, 0);\n"
"background-color: rgb(255, 255, 127);\n"
"border: 2px solid #ffff00;\n"
"border-radius: 30px\n"
"")
        self.pushButton.setObjectName("pushButton")
        Autor_MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(Autor_MainWindow)
        QtCore.QMetaObject.connectSlotsByName(Autor_MainWindow)

    def retranslateUi(self, Autor_MainWindow):
        _translate = QtCore.QCoreApplication.translate
        Autor_MainWindow.setWindowTitle(_translate("Autor_MainWindow", "Авторизация"))
        self.pushButton.setText(_translate("Autor_MainWindow", "Авторизация"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Autor_MainWindow = QtWidgets.QMainWindow()
    ui = Ui_Autor_MainWindow()
    ui.setupUi(Autor_MainWindow)
    Autor_MainWindow.show()
    sys.exit(app.exec())
